### ISSUE TITLE
StructurizrClient.get_workspace() breaks on request.url.full_path

### ISSUE THREAD

**Issue by yt-ms** [Midnighter/structurizr-python#38]
#### Problem description

When invoking `StructurizrClient.get_workspace()`, an error occurs because `httpx.URL` does not have an attribute `full_path`.

Checking [the source](https://github.com/encode/httpx/blob/master/httpx/_models.py), this definitely does not exist.

#### Code Sample

Create a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve).

```python
from structurizr.api import StructurizrClientSettings, StructurizrClient
settings = StructurizrClientSettings(url="http://a.b.c.com:8080/api", workspace_id=1, api_key="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", api_secret="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", user="structurizr")
client = StructurizrClient(settings=settings)
client.get_workspace()
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\tordoff\dev\structurizr-python\src\structurizr\api\structurizr_client.py", line 136, in get_workspace
    request.headers.update(self._add_headers(request.url.full_path))
AttributeError: 'URL' object has no attribute 'full_path'
```

### Context

<details>

```
System Information
==================
OS         Windows
OS-release      10
Python       3.7.5

Package Versions
================
depinfo                                 1.5.4
httpx                                  0.15.3
ordered-set                               3.1
pip                                    20.2.3
pydantic                                1.6.1
python-dotenv                          0.14.0
setuptools                             41.2.0
structurizr-python 0.0.1rc4+98.g8268b96.dirty
```

</details>

**Comment by Midnighter** [comment]
It's still in the docs https://www.python-httpx.org/api/#url this is strange.

**Comment by Midnighter** [comment]
Okay, probably happened in the 0.15 release if I follow changes in this https://github.com/encode/httpx/issues/1275

**Comment by yt-ms** [comment]
Yeah, after a bit of experimentation, `request.url.raw_path.decode('ascii')` seems to do the trick.  I'll create a PR.
